# Generated by Django 5.2.1 on 2025-05-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zecapp', '0004_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
